#!/usr/bin/env sh
# Context Harbor — code graph self-setup.
#
# Generated by Context Harbor (setup_code_graph MCP tool) for project
# "GGUF-Switchboard". Do not hand-edit — regenerate instead.
#
# Usage: sh ./ch-code-graph-setup.sh [REPO_DIR...]
#   Each REPO_DIR is analyzed and pushed as its own repository row under the
#   same project (frontend + backend + microservices each get an index).
#   Defaults to the current directory when no dirs are given.
#
# Auth: reuses the bearer MCP API key your harness already uses for the
#   context-harbor MCP server — no new key, never ask the user for one.
#   Resolution order: CH_MCP_TOKEN env wins; otherwise the script auto-detects
#   the key from your harness MCP config (any file mentioning "context-harbor"
#   under the known opencode / Claude Code / Cursor / Codex / VS Code /
#   Claude Desktop locations). Export CH_MCP_TOKEN only to override.
#
# Branch policy: on first run per repo the script ASKS which branch to index
# (stdin prompt; defaults to origin HEAD). The answer is saved to
# .ch-code-graph-branch next to the checkout, so later runs reuse it without
# asking. Override any run with CH_BRANCH=<branch> (env wins over the file).
# This handles repos whose deployed branch (e.g. dev) differs from the git
# default (e.g. main): answer once, every later sync follows it.
# Non-interactive runs (stdin not a TTY, e.g. agent harnesses) skip the
# prompt and fall back to origin HEAD.
#
# Prerequisites: git, curl, and tar (zip extraction on Windows uses tar or
#   powershell). Node is NOT required: the script installs the self-hosted
#   'ch' CLI binary from THIS server (code/cli/download/<platform>) with the
#   reused MCP key, then runs 'ch code setup' (server analyzer bundle) +
#   'ch code analyze'. No npm registry, no GitHub, no public package — every
#   byte comes from your ContextHarbor deployment. A 'ch' / 'context-harbor'
#   binary already on PATH is reused as-is.
#
# Steps per repo: ensure ch CLI → ensure analyzer → analyze → get-or-create
#                 repository row → upload bundle → poll job to ready.
set -eu

if [ "$#" -gt 0 ]; then
  REPO_DIRS="$@"
else
  REPO_DIRS="."
fi

# Reuse the harness MCP key: CH_MCP_TOKEN env wins, else auto-detect from the
# agent harness MCP config (the same key that authenticated setup_code_graph).
# Only files mentioning "context-harbor" are considered, so other servers'
# tokens are never picked up. Never ask the user for a new key.
resolve_ch_mcp_token() {
  for _f in     "${OPENCODE_CONFIG:-}"     "./opencode.json" "./opencode.jsonc" "./.opencode/opencode.json" "./.opencode/opencode.jsonc" "${HOME:-}/.config/opencode/opencode.json" "${HOME:-}/.config/opencode/opencode.jsonc"     "./.mcp.json" "${HOME:-}/.claude.json"     "./.cursor/mcp.json" "${HOME:-}/.cursor/mcp.json"     "./.codex/config.toml" "${HOME:-}/.codex/config.toml"     "./.vscode/mcp.json"     "${HOME:-}/Library/Application Support/Claude/claude_desktop_config.json" "${HOME:-}/.config/Claude/claude_desktop_config.json"; do
    [ -n "$_f" ] || continue
    [ -f "$_f" ] || continue
    grep -q 'context-harbor' "$_f" 2>/dev/null || continue
    _tok="$(grep -oE 'Bearer ch_[A-Za-z0-9_-]{43}' "$_f" 2>/dev/null | head -n 1 | sed 's/^Bearer //')"
    if [ -z "$_tok" ]; then
      _tok="$(grep -oE 'Bearer [0-9a-fA-F]{64}' "$_f" 2>/dev/null | head -n 1 | sed 's/^Bearer //')"
    fi
    if [ -z "$_tok" ]; then
      _tok="$(grep -oE 'Bearer [A-Za-z0-9._~+/=-]{20,}' "$_f" 2>/dev/null | head -n 1 | sed 's/^Bearer //')"
    fi
    if [ -n "$_tok" ]; then
      printf '%s' "$_tok"
      return 0
    fi
  done
  return 1
}

if [ -z "${CH_MCP_TOKEN:-}" ]; then
  _AUTO_TOKEN="$(resolve_ch_mcp_token 2>/dev/null || true)"
  if [ -n "$_AUTO_TOKEN" ]; then
    CH_MCP_TOKEN="$_AUTO_TOKEN"
    export CH_MCP_TOKEN
    echo "Reused MCP API key from harness MCP config (CH_MCP_TOKEN was unset)."
  else
    echo "CH_MCP_TOKEN is not set and no harness MCP config containing a context-harbor bearer key was found." >&2
    echo "Reuse the bearer key from your harness MCP settings for context-harbor (opencode.json, .mcp.json, ~/.claude.json, mcp.json, or config.toml) by exporting CH_MCP_TOKEN — do not create a new key." >&2
    exit 1
  fi
fi

command -v git >/dev/null 2>&1 || { echo "git is required." >&2; exit 1; }
command -v curl >/dev/null 2>&1 || { echo "curl is required." >&2; exit 1; }

# Detect platform for the self-hosted ch CLI download.
UNAME_S="$(uname -s)"
UNAME_M="$(uname -m)"
case "$UNAME_S" in
  Darwin) DL_OS="darwin" ;;
  Linux) DL_OS="linux" ;;
  MINGW*|MSYS*|CYGWIN*|Windows_NT) DL_OS="win32" ;;
  *) DL_OS="" ;;
esac
case "$UNAME_M" in
  x86_64|amd64) DL_ARCH="x64" ;;
  arm64|aarch64) DL_ARCH="arm64" ;;
  *) DL_ARCH="" ;;
esac

# Self-hosted ch CLI: every byte comes from THIS server, zero public
# registry/npm/GitHub. Archive layout per platform (built with
# 'node scripts/build-cli-binaries.mjs'):
#   ch-<os>-<arch>/bin/ch[.cmd]  launcher (bundled node runtime + cli.cjs)
#   ch-<os>-<arch>/node[.exe]    official nodejs.org runtime for the platform
#   ch-<os>-<arch>/lib/cli.cjs   tree-shaken 'ch code' closure (esbuild,
#                                zero runtime node_modules)
# Resolution order:
#  1. 'ch' / 'context-harbor' already on PATH → reused as-is;
#  2. previously installed self-hosted tree (~/.ch/bin/ch-<os>-<arch>) → reused;
#  3. download ch-<os>-<arch> archive from code/cli/download/<platform>
#     with the reused MCP key, verify sha when the server reports it
#     (X-ChCli-Sha256 header), extract under ~/.ch/bin.
# 'ch code setup' then fetches the analyzer bundle from the same server
# (same MCP key); 'ch code analyze' produces the .chcode bundle. No system
# node, no npx, no npm install — the bundled runtime does everything.
CH_HOME="${CH_HOME:-$HOME/.ch}"
CH_CLI_DIR="$CH_HOME/bin/ch-$DL_OS-$DL_ARCH"
CH_BIN="$CH_CLI_DIR/bin/ch"
if [ "$DL_OS" = "win32" ]; then
  CH_BIN="$CH_BIN.cmd"
fi
CH_ANALYZE_PREFIX=""
SETUP_ENV="CH_MCP_TOKEN="$CH_MCP_TOKEN" CH_SERVER_URL="https://contextharbor.home.pradeepcg.com""
use_path_ch() {
  if command -v ch >/dev/null 2>&1; then
    CH_ANALYZE_PREFIX="ch code analyze"
    return 0
  fi
  if command -v context-harbor >/dev/null 2>&1; then
    CH_ANALYZE_PREFIX="context-harbor code analyze"
    return 0
  fi
  return 1
}
ensure_selfhosted_ch() {
  if [ -f "$CH_BIN" ]; then
    case "$CH_BIN" in
      *.cmd) ;;
      *) chmod +x "$CH_BIN" 2>/dev/null || true ;;
    esac
    CH_ANALYZE_PREFIX=""$CH_BIN" code analyze"
    echo "ch CLI is ready ($CH_BIN)."
    return 0
  fi
  if [ -z "$DL_OS" ] || [ -z "$DL_ARCH" ]; then
    echo "Unsupported platform ($UNAME_S/$UNAME_M) and no ch CLI on PATH." >&2
    echo "Install manually: ask your ContextHarbor admin for a ch binary." >&2
    exit 1
  fi
  echo "Downloading self-hosted ch CLI for $DL_OS-$DL_ARCH from this server..."
  mkdir -p "$CH_HOME/bin" || exit 1
  if [ "$DL_OS" = "win32" ]; then
    _CH_ARCHIVE="$CH_HOME/bin/.dl-ch-$DL_OS-$DL_ARCH.zip"
  else
    _CH_ARCHIVE="$CH_HOME/bin/.dl-ch-$DL_OS-$DL_ARCH.tar.gz"
  fi
  _HDRS="$CH_HOME/bin/.dl-ch-headers"
  if ! curl -sS -f -D "$_HDRS" -o "$_CH_ARCHIVE" -H "Authorization: Bearer $CH_MCP_TOKEN" "https://contextharbor.home.pradeepcg.com/api/pradeepcgtech/code/cli/download/$DL_OS-$DL_ARCH"; then
    echo "This server has no ch CLI bundle for $DL_OS-$DL_ARCH (HTTP error above)." >&2
    echo "Ask your ContextHarbor admin to run: node scripts/build-cli-binaries.mjs" >&2
    echo "then place the archives in cli_binaries/ and redeploy." >&2
    rm -f "$_HDRS"
    exit 1
  fi
  _EXPECT_SHA="$(grep -i '^X-ChCli-Sha256:' "$_HDRS" 2>/dev/null | tr -d '\r' | awk '{print $2}')"
  rm -f "$_HDRS"
  if [ -n "$_EXPECT_SHA" ] && [ "$_EXPECT_SHA" != "pending-first-build" ]; then
    if command -v sha256sum >/dev/null 2>&1; then
      _GOT_SHA="$(sha256sum "$_CH_ARCHIVE" | awk '{print $1}')"
    elif command -v shasum >/dev/null 2>&1; then
      _GOT_SHA="$(shasum -a 256 "$_CH_ARCHIVE" | awk '{print $1}')"
    else
      _GOT_SHA=""
    fi
    if [ -n "$_GOT_SHA" ] && [ "$_GOT_SHA" != "$_EXPECT_SHA" ]; then
      echo "SHA256 mismatch for ch CLI archive: refusing to install." >&2
      rm -f "$_CH_ARCHIVE"
      exit 1
    fi
  fi
  case "$_CH_ARCHIVE" in
    *.zip)
      if command -v tar >/dev/null 2>&1 && tar -xf "$_CH_ARCHIVE" -C "$CH_HOME/bin" 2>/dev/null; then
        :
      else
        powershell -Command "Expand-Archive -Force '$_CH_ARCHIVE' '$CH_HOME/bin'" || {
          echo "Failed to extract $_CH_ARCHIVE." >&2
          exit 1
        }
      fi
      ;;
    *)
      command -v tar >/dev/null 2>&1 || { echo "tar is required." >&2; exit 1; }
      tar -xzf "$_CH_ARCHIVE" -C "$CH_HOME/bin" || {
        echo "Failed to extract $_CH_ARCHIVE." >&2
        exit 1
      }
      ;;
  esac
  rm -f "$_CH_ARCHIVE"
  case "$CH_BIN" in
    *.cmd) ;;
    *) chmod +x "$CH_BIN" 2>/dev/null || true ;;
  esac
  if [ ! -f "$CH_BIN" ]; then
    echo "ch CLI install did not yield $CH_BIN (archive layout changed?)." >&2
    exit 1
  fi
  CH_ANALYZE_PREFIX=""$CH_BIN" code analyze"
  echo "ch CLI ready from https://contextharbor.home.pradeepcg.com ($CH_BIN)."
}

CH_SETUP_CMD=""
if use_path_ch; then
  if command -v ch >/dev/null 2>&1; then
    CH_SETUP_CMD="env $SETUP_ENV ch code setup --server-url "https://contextharbor.home.pradeepcg.com""
  else
    CH_SETUP_CMD="env $SETUP_ENV context-harbor code setup --server-url "https://contextharbor.home.pradeepcg.com""
  fi
  echo "Reusing ch CLI from PATH."
else
  ensure_selfhosted_ch
  # shellcheck disable=SC2086
  CH_SETUP_CMD="env $SETUP_ENV "$CH_BIN" code setup --server-url "https://contextharbor.home.pradeepcg.com""
fi

if [ -n "$DL_OS" ] && [ -n "$DL_ARCH" ]; then
  echo "ch CLI platform: $DL_OS-$DL_ARCH (server: https://contextharbor.home.pradeepcg.com/api/pradeepcgtech/code/cli/download/$DL_OS-$DL_ARCH)"
fi

echo "[0/4] Ensuring ch CLI + code analyzer..."
# shellcheck disable=SC2086
sh -c "$CH_SETUP_CMD"

for REPO_DIR in $REPO_DIRS; do
echo "=== Repository: $REPO_DIR ==="

# --- Repository name: origin remote basename, else checkout dir basename ---
REPO_NAME=""
if git -C "$REPO_DIR" remote get-url origin >/dev/null 2>&1; then
  REMOTE_URL="$(git -C "$REPO_DIR" remote get-url origin)"
  REPO_NAME="$(basename "$REMOTE_URL" .git)"
fi
if [ -z "$REPO_NAME" ]; then
  REPO_NAME="$(basename "$(cd "$REPO_DIR" && pwd)")"
fi

# Branch to index: CH_BRANCH env wins; else the saved .ch-code-graph-branch
# file from a previous run; else ask on first run (interactive TTY only);
# else origin HEAD; else main.
BRANCH_FILE="$REPO_DIR/.ch-code-graph-branch"
REMOTE_HEAD="$(git -C "$REPO_DIR" symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@')"
if [ -n "${CH_BRANCH:-}" ]; then
  DEFAULT_BRANCH="$CH_BRANCH"
elif [ -f "$BRANCH_FILE" ] && [ -n "$(cat "$BRANCH_FILE" 2>/dev/null | tr -d '[:space:]')" ]; then
  DEFAULT_BRANCH="$(cat "$BRANCH_FILE" | tr -d '[:space:]')"
  echo "Using saved index branch '$DEFAULT_BRANCH' from $BRANCH_FILE (CH_BRANCH overrides)."
else
  SUGGESTED="${REMOTE_HEAD:-main}"
  if [ -t 0 ]; then
    printf "Which branch should Context Harbor index for $REPO_NAME? [$SUGGESTED] " >&2
    read -r ANSWER </dev/tty || ANSWER=""
    if [ -z "$ANSWER" ]; then
      DEFAULT_BRANCH="$SUGGESTED"
    else
      DEFAULT_BRANCH="$ANSWER"
    fi
    printf '%s\n' "$DEFAULT_BRANCH" > "$BRANCH_FILE"
    echo "Saved '$DEFAULT_BRANCH' to $BRANCH_FILE — delete the file to be asked again."
  else
    DEFAULT_BRANCH="$SUGGESTED"
    echo "Non-interactive run: indexing '$DEFAULT_BRANCH'. Set CH_BRANCH to override."
  fi
fi
CHECKED_OUT="$(git -C "$REPO_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "$DEFAULT_BRANCH")"
if [ "$CHECKED_OUT" != "$DEFAULT_BRANCH" ]; then
  echo "NOTE: checkout is on '$CHECKED_OUT' but indexing '$DEFAULT_BRANCH'." >&2
fi
COMMIT_SHA="$(git -C "$REPO_DIR" rev-parse "$DEFAULT_BRANCH" 2>/dev/null || git -C "$REPO_DIR" rev-parse HEAD 2>/dev/null || echo unknown)"

echo "[1/4] Analyzing $REPO_DIR..."
# Always the self-hosted ch CLI: step [0/4] above guarantees CH_ANALYZE_PREFIX
# points at a working 'ch code analyze' (PATH reuse or server download), and
# 'ch code setup' fetched the analyzer bundle from the same server. No npx,
# no standalone-analyzer fallback — the analyzer always comes from the
# server bundle.
BUNDLE_PATH=""
# shellcheck disable=SC2086
BUNDLE_PATH="$(sh -c "$CH_ANALYZE_PREFIX "$REPO_DIR"" 2>&1 | sed -n 's/^Bundle written to //p' | tail -1)"
if [ -z "$BUNDLE_PATH" ]; then
  # analyze prints the path; fall back to <abs-repo>.chcode
  BUNDLE_PATH="$(cd "$REPO_DIR" && pwd).chcode"
fi

echo "[2/4] Registering repository $REPO_NAME (default branch: $DEFAULT_BRANCH)..."
REPO_RESP="$(curl -sS -X POST "https://contextharbor.home.pradeepcg.com/api/pradeepcgtech/projects/7/repositories/get-or-create" \
  -H "Authorization: Bearer $CH_MCP_TOKEN" \
  -H 'Content-Type: application/json' \
  -d "$(printf '{"name":%s,"defaultBranch":%s}' "$(printf '%s' "$REPO_NAME" | sed 's/"/\\"/g')" "$(printf '%s' "$DEFAULT_BRANCH" | sed 's/"/\\"/g')")")"
REPO_ID="$(printf '%s' "$REPO_RESP" | sed -n 's/.*"id":\([0-9][0-9]*\).*/\1/p')"
if [ -z "$REPO_ID" ]; then
  echo "Repository registration failed: $REPO_RESP" >&2
  exit 1
fi
echo "Repository id: $REPO_ID"

echo "[3/4] Uploading bundle $BUNDLE_PATH..."
UPLOAD_RESP="$(curl -sS -X POST "https://contextharbor.home.pradeepcg.com/api/pradeepcgtech/projects/7/code/upload-mcp" \
  -H "Authorization: Bearer $CH_MCP_TOKEN" \
  -F "file=@$BUNDLE_PATH" \
  -F "repositoryId=$REPO_ID" \
  -F "branch=$DEFAULT_BRANCH" \
  -F "commitSha=$COMMIT_SHA")"
JOB_ID="$(printf '%s' "$UPLOAD_RESP" | sed -n 's/.*"jobId":\([0-9][0-9]*\).*/\1/p')"
if [ -z "$JOB_ID" ]; then
  echo "Upload failed: $UPLOAD_RESP" >&2
  exit 1
fi

echo "Indexing job $JOB_ID — polling..."
ATTEMPTS=0
while [ "$ATTEMPTS" -lt 120 ]; do
  ATTEMPTS=$((ATTEMPTS + 1))
  sleep 2
  JOB_POLL_BASE="https://contextharbor.home.pradeepcg.com/api/pradeepcgtech/code/jobs/"
  JOB_RESP="$(curl -sS "$JOB_POLL_BASE/$JOB_ID" -H "Authorization: Bearer $CH_MCP_TOKEN")"
  case "$JOB_RESP" in
    *'"status":"ready"'*)
      echo "Index ready: $JOB_RESP"
      break
      ;;
    *'"status":"failed"'*)
      echo "Index failed: $JOB_RESP" >&2
      exit 1
      ;;
  esac
  if [ "$ATTEMPTS" -ge 120 ]; then
    echo "Timed out waiting for job $JOB_ID" >&2
    exit 1
  fi
done
done
echo "All repositories indexed."
